spring:
  application:
    name: ecomerce
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomerce
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

