spring:
  application:
    name: ecomerce
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomerce
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
server:
  servlet:
    context-path: /api/v1
logging:
  level:
    '[org.springframework.web]': INFO
jwt:
  secret: c2VjcmV0S2V5Rm9ySldUU2lnbmluZ1B1cnBvc2VzT25seQ==
  expiration: 86400000